### PR TITLE
Only require parts of Rails actually needed

### PR DESCRIPTION
**Pull request by bdewater**
In our app we don't need Action Cable/Text/Mailbox etc and we don't want to pull it in for this gem.

It would be nice to even make Active Record optional and have a pattern to only offer functionality for Rails components used in the consuming application.

Relates to #47 but is more of a quick fix - I think it's possible to depends on Railties alone but this solves my immediate problem.

### CODE REVIEW

**Comment by bdewater** [comment]
@vinistock sorry for the late response, I was on pat leave :). I'll rebase this later this week.

Having to re-add parts of Rails explicitly to me felt like a good thing, so devs do not unintentionally add functionality relying on parts of the framework not declared as  dependencies.

**Comment by rafaelfranca** [comment]
I agree wit Bart, we should not add Rails in the Gemfile.

**Comment by bdewater** [comment]
Rebased! Seems the CLA check is broken.

**Comment by st0012** [comment]
@bdewater some dependencies seem downgraded in this PR and CI is failing due to dependency issues. Can you resolve it and push again?

**Review by st0012 — APPROVED** [review]
Thanks for the PR 👍

**Pull request merged**
